services:
  - type: web
    name: mockup-gestion-backend
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: SGE
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://mockup-gestion-backend.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ${{ postgres.PGHOST }}
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: ${{ postgres.PGDATABASE }}
      - key: DB_USERNAME
        value: ${{ postgres.PGUSER }}
      - key: DB_PASSWORD
        value: ${{ postgres.PGPASSWORD }}
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: single

databases:
  - name: mockup-gestion-postgres
    databaseName: sge_db
    user: sge_user
    plan: free
